// Demo catalog - shader sources are loaded on demand to keep the initial bundle small.

import { initializePhotorealMeshMemory } from './src/photoreal-scene-builder.js';
import { initializePbfHydrostaticMemory } from './src/pbf-scene-builder.js';
import { initializeRttnwEarthMemory } from './src/rttnw-earth-texture.js';
import { initializeNeuralSdfMemory } from './src/neural-sdf-weights.js';

export const demoGroups = {
    start: 'getting started',
    foundations: 'visual foundations',
    compiler: 'compiler showcase',
    weekend: 'ray tracing in one weekend',
    nextweek: 'ray tracing the next week',
    persistent: 'persistent memory',
    physics: 'physics',
    advanced: 'advanced rendering',
};

const autoParallel = ['AUTO PARALLEL'];

export const demoCatalog = {
    starter: {
        name: 'Starter Template',
        group: 'start',
        description: 'The minimum pixel loop, memory layout, and animation input contract.',
        features: autoParallel,
        load: () => import('./shaders/starter.as?raw'),
    },
    coordinateLab: {
        name: 'Coordinate Lab',
        group: 'start',
        description: 'Four compact studies of gradients, grids, distance, and polar coordinates.',
        features: autoParallel,
        load: () => import('./shaders/coordinate_lab.as?raw'),
    },
    xorTextureZoo: {
        name: 'XOR Texture Zoo',
        group: 'foundations',
        description: 'Eight integer and bitwise texture formulas in one editable atlas.',
        features: autoParallel,
        load: () => import('./shaders/xor_texture_zoo.as?raw'),
    },
    truchetMosaic: {
        name: 'Truchet Mosaic',
        group: 'foundations',
        description: 'A shifting maze built from hashed tile orientation and arc geometry.',
        features: autoParallel,
        load: () => import('./shaders/truchet_mosaic.as?raw'),
    },
    plasma: {
        name: 'Plasma',
        group: 'foundations',
        description: 'Layered waves separated cleanly from cosine palette mapping.',
        features: autoParallel,
        load: () => import('./shaders/plasma.as?raw'),
    },
    metaballs: {
        name: 'Metaballs',
        group: 'foundations',
        description: 'Moving implicit fields that merge into softly shaded organic forms.',
        features: autoParallel,
        load: () => import('./shaders/metaballs.as?raw'),
    },
    voronoiGlass: {
        name: 'Voronoi Stained Glass',
        group: 'foundations',
        description: 'Animated cells, luminous borders, and refraction-like color offsets.',
        features: autoParallel,
        load: () => import('./shaders/voronoi_stained_glass.as?raw'),
    },
    precisionJulia: {
        name: 'Precision Julia Orbit Traps',
        group: 'compiler',
        description: 'A morphing Julia set that intentionally exercises numeric demotion.',
        features: ['AUTO PARALLEL', 'F64 DEMOTION', 'I64'],
        load: () => import('./shaders/precision_julia.as?raw'),
    },
    simdKaleidoscope: {
        name: 'SIMD Neon Kaleidoscope',
        slug: 'simd-neon',
        group: 'compiler',
        description: 'A vectorized neon tunnel driven by direct Gasm math intrinsics.',
        features: ['AUTO PARALLEL', 'SIMD', 'MATH M0'],
        compileOptions: { mathExtension: 'M0' },
        assemblyScriptOptions: { enable: ['simd'] },
        load: () => import('./shaders/simd_neon_kaleidoscope.as?raw'),
    },
    voxelRaycaster: {
        name: 'Voxel Raycaster',
        group: 'compiler',
        description: 'Amanatides-Woo grid traversal through a procedural voxel landscape.',
        features: autoParallel,
        load: () => import('./shaders/voxel_raycaster.as?raw'),
    },
    tinySphereTracer: {
        name: 'Tiny Sphere Tracer',
        group: 'compiler',
        description: 'A compact JavaScript ray-sphere demo ported to scalar AssemblyScript.',
        features: ['AUTO PARALLEL', 'RAY TRACE'],
        load: () => import('./shaders/tiny_sphere_tracer.as?raw'),
    },
    simdPacketTracer: {
        name: 'SIMD Packet Sphere Tracer',
        slug: 'simd-packet',
        group: 'compiler',
        description: 'Four jittered primary rays intersect spheres as f32x4 packets. The SIMD exhibit is the WAT listing.',
        features: ['AUTO PARALLEL', 'SIMD', 'RAY PACKET'],
        assemblyScriptOptions: { enable: ['simd'] },
        load: () => import('./shaders/simd_packet_tracer.as?raw'),
    },
    tessendorfOcean: {
        name: 'Tessendorf FFT Ocean',
        slug: 'fft-ocean',
        group: 'compiler',
        description: 'A 256×256 Phillips spectrum inverse-FFT, staged across pair-owned butterfly dispatches.',
        features: ['AUTO PARALLEL', 'FFT', 'PERSISTENT', 'STAGED DISPATCH'],
        clock: 'step',
        load: () => import('./shaders/tessendorf_ocean.as?raw'),
    },
    computeRasterizer: {
        name: 'Compute Triangle Rasterizer',
        slug: 'compute-raster',
        group: 'compiler',
        description: 'A spinning cube and ground plane filled with barycentric coverage and a per-pixel z-test.',
        features: ['AUTO PARALLEL', 'RASTER', 'Z-TEST'],
        load: () => import('./shaders/compute_rasterizer.as?raw'),
    },
    f64MandelbrotSplit: {
        name: 'F64 Split Mandelbrot',
        slug: 'f64-split',
        group: 'compiler',
        description: 'Left half iterates in f32, right half in f64, so Results shows hot-loop demotion.',
        features: ['AUTO PARALLEL', 'F64 DEMOTION', 'SPLIT VIEW'],
        load: () => import('./shaders/f64_mandelbrot_split.as?raw'),
    },
    neuralSdf: {
        name: 'Neural SDF MLP',
        slug: 'neural-sdf',
        group: 'compiler',
        description: 'Host SGD bakes a tiny 24-32-32-1 MLP of a torus; the shader only infers and raymarches. The soft noisy ring and 16-phase tile tearing are expected — look at the WAT/WGSL matmuls, not a clean analytic SDF.',
        features: ['AUTO PARALLEL', 'MLP', 'PERSISTENT', 'RAY MARCH'],
        initializeMemory: initializeNeuralSdfMemory,
        load: () => import('./shaders/neural_sdf.as?raw'),
    },
    rtowImage: {
        name: 'Output an Image',
        group: 'weekend',
        description: 'The book\'s first 256×256 image: red right, green down, yellow corner.',
        features: autoParallel,
        load: () => import('./shaders/rtow_01_image.as?raw'),
    },
    rtowSky: {
        name: 'Rays and Sky',
        group: 'weekend',
        description: 'Viewport rays from a simple camera, letterboxed 16:9, lerped white-to-blue.',
        features: autoParallel,
        load: () => import('./shaders/rtow_02_sky.as?raw'),
    },
    rtowRedSphere: {
        name: 'Red Sphere',
        group: 'weekend',
        description: 'A quadratic ray-sphere test colors the first object as a solid red disc.',
        features: autoParallel,
        load: () => import('./shaders/rtow_03_red_sphere.as?raw'),
    },
    rtowNormals: {
        name: 'Surface Normals',
        group: 'weekend',
        description: 'The nearest positive hit maps the unit sphere normal into RGB.',
        features: autoParallel,
        load: () => import('./shaders/rtow_04_normals.as?raw'),
    },
    rtowMultiple: {
        name: 'Multiple Objects',
        group: 'weekend',
        description: 'A small sphere on a ground sphere, shaded by nearest-hit normals.',
        features: autoParallel,
        load: () => import('./shaders/rtow_05_multiple.as?raw'),
    },
    rtowAntialias: {
        name: 'Antialiasing',
        group: 'weekend',
        description: 'Four jittered samples per pixel soften the two-sphere silhouette.',
        features: autoParallel,
        load: () => import('./shaders/rtow_06_antialias.as?raw'),
    },
    rtowDiffuse: {
        name: 'Diffuse Materials',
        group: 'weekend',
        description: 'Lambertian bounces with one accumulating path per frame.',
        features: ['AUTO PARALLEL', 'PERSISTENT', 'PROGRESSIVE'],
        load: () => import('./shaders/rtow_07_diffuse.as?raw'),
    },
    rtowMetal: {
        name: 'Metal',
        group: 'weekend',
        description: 'Fuzzy metal spheres beside lambertian ground and center balls.',
        features: ['AUTO PARALLEL', 'PERSISTENT', 'PROGRESSIVE'],
        load: () => import('./shaders/rtow_08_metal.as?raw'),
    },
    rtowDielectrics: {
        name: 'Dielectrics',
        group: 'weekend',
        description: 'A hollow glass sphere with Schlick reflectance, metal, and lambert.',
        features: ['AUTO PARALLEL', 'PERSISTENT', 'PROGRESSIVE'],
        load: () => import('./shaders/rtow_09_dielectrics.as?raw'),
    },
    rtowFinal: {
        name: 'Final Render',
        group: 'weekend',
        description: 'Look-from camera, defocus blur, and a reduced weekend sphere world.',
        features: ['AUTO PARALLEL', 'PERSISTENT', 'PROGRESSIVE'],
        load: () => import('./shaders/rtow_10_final.as?raw'),
    },
    rttnwMotion: {
        name: 'Motion Blur',
        group: 'nextweek',
        description: 'Weekend sphere world with lambertian centers moving during the shutter.',
        features: ['AUTO PARALLEL', 'PERSISTENT', 'PROGRESSIVE', 'MOTION'],
        load: () => import('./shaders/rttnw_01_motion.as?raw'),
    },
    rttnwCheckers: {
        name: 'Checkered Spheres',
        group: 'nextweek',
        description: 'Two large spheres with a spatial checker texture against a solid sky.',
        features: ['AUTO PARALLEL', 'PERSISTENT', 'PROGRESSIVE'],
        load: () => import('./shaders/rttnw_02_checkers.as?raw'),
    },
    rttnwEarth: {
        name: 'Earth',
        group: 'nextweek',
        description: 'A lambertian globe sampled from a packed equirectangular texture.',
        features: ['AUTO PARALLEL', 'PERSISTENT', 'PROGRESSIVE', 'TEXTURE'],
        initializeMemory: initializeRttnwEarthMemory,
        load: () => import('./shaders/rttnw_03_earth.as?raw'),
    },
    rttnwPerlin: {
        name: 'Perlin Marble',
        group: 'nextweek',
        description: 'Hash-based Perlin turbulence marble on a ground sphere and globe.',
        features: ['AUTO PARALLEL', 'PERSISTENT', 'PROGRESSIVE'],
        load: () => import('./shaders/rttnw_04_perlin.as?raw'),
    },
    rttnwQuads: {
        name: 'Quads',
        group: 'nextweek',
        description: 'Five lambertian parallelograms from the book, square frame.',
        features: ['AUTO PARALLEL', 'PERSISTENT', 'PROGRESSIVE'],
        load: () => import('./shaders/rttnw_05_quads.as?raw'),
    },
    rttnwLights: {
        name: 'Simple Light',
        group: 'nextweek',
        description: 'Marble spheres lit by an emissive quad and sphere against black.',
        features: ['AUTO PARALLEL', 'PERSISTENT', 'PROGRESSIVE'],
        load: () => import('./shaders/rttnw_06_lights.as?raw'),
    },
    rttnwCornell: {
        name: 'Cornell Box',
        group: 'nextweek',
        description: 'Book Cornell walls, ceiling light, and two rotated white boxes.',
        features: ['AUTO PARALLEL', 'PERSISTENT', 'PROGRESSIVE'],
        load: () => import('./shaders/rttnw_07_cornell.as?raw'),
    },
    rttnwSmoke: {
        name: 'Cornell Smoke',
        group: 'nextweek',
        description: 'Cornell box with constant-density black and white media.',
        features: ['AUTO PARALLEL', 'PERSISTENT', 'PROGRESSIVE'],
        load: () => import('./shaders/rttnw_08_smoke.as?raw'),
    },
    rttnwFinal: {
        name: 'Final Scene',
        group: 'nextweek',
        description: 'Reduced Next Week final: boxes, instances, earth, volumes, and motion.',
        features: ['AUTO PARALLEL', 'PERSISTENT', 'PROGRESSIVE', 'TEXTURE'],
        initializeMemory: initializeRttnwEarthMemory,
        load: () => import('./shaders/rttnw_09_final.as?raw'),
    },
    persistentLife: {
        name: 'Persistent Life',
        group: 'persistent',
        description: 'Conway Life with GPU-resident ping-pong state.',
        features: ['AUTO PARALLEL', 'PERSISTENT'],
        load: () => import('./shaders/persistent_life.as?raw'),
    },
    persistentHeat: {
        name: 'Persistent Heat Diffusion',
        group: 'persistent',
        description: 'Retained heat diffusion with animated sources.',
        features: ['AUTO PARALLEL', 'PERSISTENT'],
        load: () => import('./shaders/persistent_heat.as?raw'),
    },
    persistentCyclic: {
        name: 'Persistent Cyclic Automata',
        group: 'persistent',
        description: 'Sixteen-state cellular waves that chase across a toroidal field.',
        features: ['AUTO PARALLEL', 'PERSISTENT'],
        load: () => import('./shaders/persistent_cyclic.as?raw'),
    },
    rippleTank: {
        name: 'Interactive Ripple Tank',
        group: 'persistent',
        description: 'Pointer-driven refraction over procedural wet cobblestone.',
        features: ['AUTO PARALLEL', 'PERSISTENT', 'I16 MEMORY', 'POINTER'],
        clock: 'step',
        load: () => import('./shaders/interactive_ripple_tank.as?raw'),
    },
    grayScottCoral: {
        name: 'Gray-Scott Coral Lab',
        group: 'persistent',
        description: 'Paint reaction chemicals into a growing coral-like simulation.',
        features: ['AUTO PARALLEL', 'PERSISTENT', 'U16 MEMORY', 'POINTER'],
        load: () => import('./shaders/gray_scott_coral.as?raw'),
    },
    flowFieldInk: {
        name: 'Flow-Field Ink',
        group: 'persistent',
        description: 'Colored ink transported through a procedural curl field.',
        features: ['AUTO PARALLEL', 'PERSISTENT', 'F32 STATE', 'POINTER'],
        load: () => import('./shaders/flow_field_ink.as?raw'),
    },
    pbfHydrostaticColumn: {
        name: 'PBF Hydrostatic Column',
        group: 'physics',
        description: 'A 3,800-particle PBF drop flowing around a raised static sphere with a fused metaball surface.',
        features: ['AUTO PARALLEL', '3D PBF', 'METABALL SURFACE', 'PERSISTENT', 'DIAGNOSTICS'],
        clock: 'step',
        initializeMemory: initializePbfHydrostaticMemory,
        load: () => import('./shaders/pbf_fluid_dynamics.as?raw'),
    },
    compilerGridSph: {
        name: '8K Compiler Grid SPH',
        slug: '8k-compiler-grid-sph',
        group: 'physics',
        description: '8,192 SPH particles use a compiler-generated cell-owned grid and linear-memory density raymarcher.',
        features: ['AUTO PARALLEL', '8K SPH', 'CELL-OWNED GRID', 'VOLUME RAYMARCH', 'PERSISTENT'],
        clock: 'step',
        load: () => import('./shaders/grid_sph.as?raw'),
    },
    rigidBallsSdf: {
        name: 'Rigid Ball SDF Physics',
        group: 'physics',
        description: 'Elastic wall-bounce rigid spheres raymarched as signed distance fields.',
        features: ['AUTO PARALLEL', 'SDF', 'PHYSICS'],
        load: () => import('./shaders/rigid_balls_sdf.as?raw'),
    },
    cableCylinderDynamics: {
        name: 'Cable Drop Lab',
        slug: 'cable-drop-lab',
        group: 'physics',
        description: 'A bundle of Verlet cables falls and settles over a cylinder with soft shadows and ambient occlusion.',
        features: ['AUTO PARALLEL', 'VERLET CABLES', 'PERSISTENT', 'SOFT SHADOWS', 'AMBIENT OCCLUSION'],
        clock: 'step',
        load: () => import('./shaders/cable_cylinder_dynamics.as?raw'),
    },
    flagshipSdfScene: {
        name: 'Raymarched SDF Scene',
        group: 'advanced',
        description: 'Distance fields, soft shadows, ambient occlusion, fog, and reflection.',
        features: autoParallel,
        load: () => import('./shaders/flagship_sdf_scene.as?raw'),
    },
    flagshipMandelbrot: {
        name: 'Deep Mandelbrot Zoom',
        group: 'advanced',
        description: 'A supersampled, smoothly colored fractal stress test.',
        features: autoParallel,
        load: () => import('./shaders/flagship_mandelbrot.as?raw'),
    },
    flagshipClouds: {
        name: 'Volumetric Clouds',
        group: 'advanced',
        description: 'Layered volumetric clouds, atmospheric light, and reflective water.',
        features: autoParallel,
        load: () => import('./shaders/flagship_clouds.as?raw'),
    },
    flagshipFire: {
        name: 'Turbulent Fire',
        group: 'advanced',
        description: 'Domain-warped volumetric flame, sparks, glow, and tone mapping.',
        features: autoParallel,
        load: () => import('./shaders/flagship_fire.as?raw'),
    },
    proceduralPlanet: {
        name: 'Procedural Planet',
        group: 'advanced',
        description: 'A rotating world with displaced terrain, ocean, atmosphere, and volumetric clouds.',
        features: ['AUTO PARALLEL', 'MATH M0'],
        compileOptions: { mathExtension: 'M0' },
        load: () => import('./shaders/procedural_planet.as?raw'),
    },
    cornellBoxGi: {
        name: 'Cornell Box (Path Tracing)',
        group: 'advanced',
        description: 'A high-sample path tracer that computes a fresh estimate each frame.',
        features: autoParallel,
        load: () => import('./shaders/cornell_box_gi.as?raw'),
    },
    photorealMeshPathTracer: {
        name: 'Photoreal Mesh Path Tracer',
        group: 'advanced',
        description: 'Progressive product-studio path tracing over packed mesh triangles and a threaded BVH.',
        features: ['AUTO PARALLEL', 'PERSISTENT', 'PROGRESSIVE', 'BVH'],
        initializeMemory: initializePhotorealMeshMemory,
        load: () => import('./shaders/photoreal_mesh_path_tracer.as?raw'),
    },
    progressivePathTracer: {
        name: 'Progressive Path Tracer',
        group: 'advanced',
        description: 'A material study that accumulates global illumination across frames.',
        features: ['AUTO PARALLEL', 'PERSISTENT', 'PROGRESSIVE'],
        load: () => import('./shaders/progressive_path_tracer.as?raw'),
    },
};

const sourceCache = new Map();

export async function loadDemoSource(demoId) {
    if (sourceCache.has(demoId)) return sourceCache.get(demoId);

    const entry = demoCatalog[demoId];
    if (!entry) throw new Error(`Unknown demo: ${demoId}`);

    const mod = await entry.load();
    const code = mod.default;
    sourceCache.set(demoId, code);
    return code;
}
